/*
 * MetaFab API
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CreateCollectionItemRequestAttributesInner
 */
public class CreateCollectionItemRequestAttributesInnerTest {
    private final CreateCollectionItemRequestAttributesInner model = new CreateCollectionItemRequestAttributesInner();

    /**
     * Model tests for CreateCollectionItemRequestAttributesInner
     */
    @Test
    public void testCreateCollectionItemRequestAttributesInner() {
        // TODO: test CreateCollectionItemRequestAttributesInner
    }

    /**
     * Test the property 'traitType'
     */
    @Test
    public void traitTypeTest() {
        // TODO: test traitType
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

}
