/*
 * MetaFab API
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for GetPlayerData200Response
 */
public class GetPlayerData200ResponseTest {
    private final GetPlayerData200Response model = new GetPlayerData200Response();

    /**
     * Model tests for GetPlayerData200Response
     */
    @Test
    public void testGetPlayerData200Response() {
        // TODO: test GetPlayerData200Response
    }

    /**
     * Test the property 'protectedData'
     */
    @Test
    public void protectedDataTest() {
        // TODO: test protectedData
    }

    /**
     * Test the property 'publicData'
     */
    @Test
    public void publicDataTest() {
        // TODO: test publicData
    }

}
