/*
 * MetaFab API
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PublicEcosystem
 */
public class PublicEcosystemTest {
    private final PublicEcosystem model = new PublicEcosystem();

    /**
     * Model tests for PublicEcosystem
     */
    @Test
    public void testPublicEcosystem() {
        // TODO: test PublicEcosystem
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'publishedKey'
     */
    @Test
    public void publishedKeyTest() {
        // TODO: test publishedKey
    }

    /**
     * Test the property 'iconImageUrl'
     */
    @Test
    public void iconImageUrlTest() {
        // TODO: test iconImageUrl
    }

    /**
     * Test the property 'coverImageUrl'
     */
    @Test
    public void coverImageUrlTest() {
        // TODO: test coverImageUrl
    }

    /**
     * Test the property 'primaryColorHex'
     */
    @Test
    public void primaryColorHexTest() {
        // TODO: test primaryColorHex
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

}
