/*
 * MetaFab API
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for WriteContractRequestArgsInner
 */
public class WriteContractRequestArgsInnerTest {
    private final WriteContractRequestArgsInner model = new WriteContractRequestArgsInner();

    /**
     * Model tests for WriteContractRequestArgsInner
     */
    @Test
    public void testWriteContractRequestArgsInner() {
        // TODO: test WriteContractRequestArgsInner
    }

}
