/*
 * MetaFab API
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.5.1
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.WalletModel;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.metafab.client.JSON;

/**
 * AuthPlayer200ResponseAllOf
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-02-19T17:38:27.237153-05:00[America/New_York]")
public class AuthPlayer200ResponseAllOf {
  public static final String SERIALIZED_NAME_WALLET_DECRYPT_KEY = "walletDecryptKey";
  @SerializedName(SERIALIZED_NAME_WALLET_DECRYPT_KEY)
  private String walletDecryptKey;

  public static final String SERIALIZED_NAME_WALLET = "wallet";
  @SerializedName(SERIALIZED_NAME_WALLET)
  private WalletModel wallet;

  public static final String SERIALIZED_NAME_CUSTODIAL_WALLET = "custodialWallet";
  @SerializedName(SERIALIZED_NAME_CUSTODIAL_WALLET)
  private WalletModel custodialWallet;

  public AuthPlayer200ResponseAllOf() {
  }

  public AuthPlayer200ResponseAllOf walletDecryptKey(String walletDecryptKey) {
    
    this.walletDecryptKey = walletDecryptKey;
    return this;
  }

   /**
   * This field has not had a description added.
   * @return walletDecryptKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "This field has not had a description added.")

  public String getWalletDecryptKey() {
    return walletDecryptKey;
  }


  public void setWalletDecryptKey(String walletDecryptKey) {
    this.walletDecryptKey = walletDecryptKey;
  }


  public AuthPlayer200ResponseAllOf wallet(WalletModel wallet) {
    
    this.wallet = wallet;
    return this;
  }

   /**
   * Get wallet
   * @return wallet
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public WalletModel getWallet() {
    return wallet;
  }


  public void setWallet(WalletModel wallet) {
    this.wallet = wallet;
  }


  public AuthPlayer200ResponseAllOf custodialWallet(WalletModel custodialWallet) {
    
    this.custodialWallet = custodialWallet;
    return this;
  }

   /**
   * Get custodialWallet
   * @return custodialWallet
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public WalletModel getCustodialWallet() {
    return custodialWallet;
  }


  public void setCustodialWallet(WalletModel custodialWallet) {
    this.custodialWallet = custodialWallet;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthPlayer200ResponseAllOf authPlayer200ResponseAllOf = (AuthPlayer200ResponseAllOf) o;
    return Objects.equals(this.walletDecryptKey, authPlayer200ResponseAllOf.walletDecryptKey) &&
        Objects.equals(this.wallet, authPlayer200ResponseAllOf.wallet) &&
        Objects.equals(this.custodialWallet, authPlayer200ResponseAllOf.custodialWallet);
  }

  @Override
  public int hashCode() {
    return Objects.hash(walletDecryptKey, wallet, custodialWallet);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthPlayer200ResponseAllOf {\n");
    sb.append("    walletDecryptKey: ").append(toIndentedString(walletDecryptKey)).append("\n");
    sb.append("    wallet: ").append(toIndentedString(wallet)).append("\n");
    sb.append("    custodialWallet: ").append(toIndentedString(custodialWallet)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("walletDecryptKey");
    openapiFields.add("wallet");
    openapiFields.add("custodialWallet");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to AuthPlayer200ResponseAllOf
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!AuthPlayer200ResponseAllOf.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AuthPlayer200ResponseAllOf is not found in the empty JSON string", AuthPlayer200ResponseAllOf.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!AuthPlayer200ResponseAllOf.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AuthPlayer200ResponseAllOf` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if ((jsonObj.get("walletDecryptKey") != null && !jsonObj.get("walletDecryptKey").isJsonNull()) && !jsonObj.get("walletDecryptKey").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `walletDecryptKey` to be a primitive type in the JSON string but got `%s`", jsonObj.get("walletDecryptKey").toString()));
      }
      // validate the optional field `wallet`
      if (jsonObj.get("wallet") != null && !jsonObj.get("wallet").isJsonNull()) {
        WalletModel.validateJsonObject(jsonObj.getAsJsonObject("wallet"));
      }
      // validate the optional field `custodialWallet`
      if (jsonObj.get("custodialWallet") != null && !jsonObj.get("custodialWallet").isJsonNull()) {
        WalletModel.validateJsonObject(jsonObj.getAsJsonObject("custodialWallet"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AuthPlayer200ResponseAllOf.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AuthPlayer200ResponseAllOf' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AuthPlayer200ResponseAllOf> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AuthPlayer200ResponseAllOf.class));

       return (TypeAdapter<T>) new TypeAdapter<AuthPlayer200ResponseAllOf>() {
           @Override
           public void write(JsonWriter out, AuthPlayer200ResponseAllOf value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AuthPlayer200ResponseAllOf read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of AuthPlayer200ResponseAllOf given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AuthPlayer200ResponseAllOf
  * @throws IOException if the JSON string is invalid with respect to AuthPlayer200ResponseAllOf
  */
  public static AuthPlayer200ResponseAllOf fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AuthPlayer200ResponseAllOf.class);
  }

 /**
  * Convert an instance of AuthPlayer200ResponseAllOf to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

