/*
 * MetaFab API
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.metafab.client.JSON;

/**
 * ExchangeOffer
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-11-07T16:37:22.578727-08:00[America/Los_Angeles]")
public class ExchangeOffer {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private BigDecimal id;

  public static final String SERIALIZED_NAME_INPUT_COLLECTION = "inputCollection";
  @SerializedName(SERIALIZED_NAME_INPUT_COLLECTION)
  private String inputCollection;

  public static final String SERIALIZED_NAME_INPUT_COLLECTION_ITEM_IDS = "inputCollectionItemIds";
  @SerializedName(SERIALIZED_NAME_INPUT_COLLECTION_ITEM_IDS)
  private List<BigDecimal> inputCollectionItemIds = null;

  public static final String SERIALIZED_NAME_INPUT_COLLECTION_ITEM_AMOUNTS = "inputCollectionItemAmounts";
  @SerializedName(SERIALIZED_NAME_INPUT_COLLECTION_ITEM_AMOUNTS)
  private List<BigDecimal> inputCollectionItemAmounts = null;

  public static final String SERIALIZED_NAME_INPUT_CURRENCY = "inputCurrency";
  @SerializedName(SERIALIZED_NAME_INPUT_CURRENCY)
  private String inputCurrency;

  public static final String SERIALIZED_NAME_INPUT_CURRENCY_AMOUNT = "inputCurrencyAmount";
  @SerializedName(SERIALIZED_NAME_INPUT_CURRENCY_AMOUNT)
  private BigDecimal inputCurrencyAmount;

  public static final String SERIALIZED_NAME_OUTPUT_COLLECTION = "outputCollection";
  @SerializedName(SERIALIZED_NAME_OUTPUT_COLLECTION)
  private String outputCollection;

  public static final String SERIALIZED_NAME_OUTPUT_COLLECTION_ITEM_IDS = "outputCollectionItemIds";
  @SerializedName(SERIALIZED_NAME_OUTPUT_COLLECTION_ITEM_IDS)
  private List<BigDecimal> outputCollectionItemIds = null;

  public static final String SERIALIZED_NAME_OUTPUT_COLLECTION_ITEM_AMOUNTS = "outputCollectionItemAmounts";
  @SerializedName(SERIALIZED_NAME_OUTPUT_COLLECTION_ITEM_AMOUNTS)
  private List<BigDecimal> outputCollectionItemAmounts = null;

  public static final String SERIALIZED_NAME_OUTPUT_CURRENCY = "outputCurrency";
  @SerializedName(SERIALIZED_NAME_OUTPUT_CURRENCY)
  private String outputCurrency;

  public static final String SERIALIZED_NAME_OUTPUT_CURRENCY_AMOUNT = "outputCurrencyAmount";
  @SerializedName(SERIALIZED_NAME_OUTPUT_CURRENCY_AMOUNT)
  private BigDecimal outputCurrencyAmount;

  public static final String SERIALIZED_NAME_USES = "uses";
  @SerializedName(SERIALIZED_NAME_USES)
  private BigDecimal uses;

  public static final String SERIALIZED_NAME_MAX_USES = "maxUses";
  @SerializedName(SERIALIZED_NAME_MAX_USES)
  private BigDecimal maxUses;

  public static final String SERIALIZED_NAME_LAST_UPDATED_AT = "lastUpdatedAt";
  @SerializedName(SERIALIZED_NAME_LAST_UPDATED_AT)
  private BigDecimal lastUpdatedAt;

  public ExchangeOffer() {
  }

  public ExchangeOffer id(BigDecimal id) {
    
    this.id = id;
    return this;
  }

   /**
   * The id of this offer.
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The id of this offer.")

  public BigDecimal getId() {
    return id;
  }


  public void setId(BigDecimal id) {
    this.id = id;
  }


  public ExchangeOffer inputCollection(String inputCollection) {
    
    this.inputCollection = inputCollection;
    return this;
  }

   /**
   * The address of the ERC1155 of MetaFab game items contract for input items required by this offer.
   * @return inputCollection
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The address of the ERC1155 of MetaFab game items contract for input items required by this offer.")

  public String getInputCollection() {
    return inputCollection;
  }


  public void setInputCollection(String inputCollection) {
    this.inputCollection = inputCollection;
  }


  public ExchangeOffer inputCollectionItemIds(List<BigDecimal> inputCollectionItemIds) {
    
    this.inputCollectionItemIds = inputCollectionItemIds;
    return this;
  }

  public ExchangeOffer addInputCollectionItemIdsItem(BigDecimal inputCollectionItemIdsItem) {
    if (this.inputCollectionItemIds == null) {
      this.inputCollectionItemIds = new ArrayList<>();
    }
    this.inputCollectionItemIds.add(inputCollectionItemIdsItem);
    return this;
  }

   /**
   * An array of item ids from the input collection that are required for this offer.
   * @return inputCollectionItemIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An array of item ids from the input collection that are required for this offer.")

  public List<BigDecimal> getInputCollectionItemIds() {
    return inputCollectionItemIds;
  }


  public void setInputCollectionItemIds(List<BigDecimal> inputCollectionItemIds) {
    this.inputCollectionItemIds = inputCollectionItemIds;
  }


  public ExchangeOffer inputCollectionItemAmounts(List<BigDecimal> inputCollectionItemAmounts) {
    
    this.inputCollectionItemAmounts = inputCollectionItemAmounts;
    return this;
  }

  public ExchangeOffer addInputCollectionItemAmountsItem(BigDecimal inputCollectionItemAmountsItem) {
    if (this.inputCollectionItemAmounts == null) {
      this.inputCollectionItemAmounts = new ArrayList<>();
    }
    this.inputCollectionItemAmounts.add(inputCollectionItemAmountsItem);
    return this;
  }

   /**
   * An array of amounts for each item id for the input collection that are required to use this offer.
   * @return inputCollectionItemAmounts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An array of amounts for each item id for the input collection that are required to use this offer.")

  public List<BigDecimal> getInputCollectionItemAmounts() {
    return inputCollectionItemAmounts;
  }


  public void setInputCollectionItemAmounts(List<BigDecimal> inputCollectionItemAmounts) {
    this.inputCollectionItemAmounts = inputCollectionItemAmounts;
  }


  public ExchangeOffer inputCurrency(String inputCurrency) {
    
    this.inputCurrency = inputCurrency;
    return this;
  }

   /**
   * The address of the ERC20 or MetaFab game currency for the currency required by this offer.
   * @return inputCurrency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The address of the ERC20 or MetaFab game currency for the currency required by this offer.")

  public String getInputCurrency() {
    return inputCurrency;
  }


  public void setInputCurrency(String inputCurrency) {
    this.inputCurrency = inputCurrency;
  }


  public ExchangeOffer inputCurrencyAmount(BigDecimal inputCurrencyAmount) {
    
    this.inputCurrencyAmount = inputCurrencyAmount;
    return this;
  }

   /**
   * The amount of currency required by this offer.
   * @return inputCurrencyAmount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The amount of currency required by this offer.")

  public BigDecimal getInputCurrencyAmount() {
    return inputCurrencyAmount;
  }


  public void setInputCurrencyAmount(BigDecimal inputCurrencyAmount) {
    this.inputCurrencyAmount = inputCurrencyAmount;
  }


  public ExchangeOffer outputCollection(String outputCollection) {
    
    this.outputCollection = outputCollection;
    return this;
  }

   /**
   * The address of the ERC1155 of MetaFab game items contract for output items given by this offer.
   * @return outputCollection
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The address of the ERC1155 of MetaFab game items contract for output items given by this offer.")

  public String getOutputCollection() {
    return outputCollection;
  }


  public void setOutputCollection(String outputCollection) {
    this.outputCollection = outputCollection;
  }


  public ExchangeOffer outputCollectionItemIds(List<BigDecimal> outputCollectionItemIds) {
    
    this.outputCollectionItemIds = outputCollectionItemIds;
    return this;
  }

  public ExchangeOffer addOutputCollectionItemIdsItem(BigDecimal outputCollectionItemIdsItem) {
    if (this.outputCollectionItemIds == null) {
      this.outputCollectionItemIds = new ArrayList<>();
    }
    this.outputCollectionItemIds.add(outputCollectionItemIdsItem);
    return this;
  }

   /**
   * An array of item ids from the output collection that are given for this offer.
   * @return outputCollectionItemIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An array of item ids from the output collection that are given for this offer.")

  public List<BigDecimal> getOutputCollectionItemIds() {
    return outputCollectionItemIds;
  }


  public void setOutputCollectionItemIds(List<BigDecimal> outputCollectionItemIds) {
    this.outputCollectionItemIds = outputCollectionItemIds;
  }


  public ExchangeOffer outputCollectionItemAmounts(List<BigDecimal> outputCollectionItemAmounts) {
    
    this.outputCollectionItemAmounts = outputCollectionItemAmounts;
    return this;
  }

  public ExchangeOffer addOutputCollectionItemAmountsItem(BigDecimal outputCollectionItemAmountsItem) {
    if (this.outputCollectionItemAmounts == null) {
      this.outputCollectionItemAmounts = new ArrayList<>();
    }
    this.outputCollectionItemAmounts.add(outputCollectionItemAmountsItem);
    return this;
  }

   /**
   * An array of amounts for each item id for the output collection that are given by this offer.
   * @return outputCollectionItemAmounts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An array of amounts for each item id for the output collection that are given by this offer.")

  public List<BigDecimal> getOutputCollectionItemAmounts() {
    return outputCollectionItemAmounts;
  }


  public void setOutputCollectionItemAmounts(List<BigDecimal> outputCollectionItemAmounts) {
    this.outputCollectionItemAmounts = outputCollectionItemAmounts;
  }


  public ExchangeOffer outputCurrency(String outputCurrency) {
    
    this.outputCurrency = outputCurrency;
    return this;
  }

   /**
   * The address of the ERC20 or MetaFab game currency for the output currency given by this offer.
   * @return outputCurrency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The address of the ERC20 or MetaFab game currency for the output currency given by this offer.")

  public String getOutputCurrency() {
    return outputCurrency;
  }


  public void setOutputCurrency(String outputCurrency) {
    this.outputCurrency = outputCurrency;
  }


  public ExchangeOffer outputCurrencyAmount(BigDecimal outputCurrencyAmount) {
    
    this.outputCurrencyAmount = outputCurrencyAmount;
    return this;
  }

   /**
   * The amount of currency given by this offer.
   * @return outputCurrencyAmount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The amount of currency given by this offer.")

  public BigDecimal getOutputCurrencyAmount() {
    return outputCurrencyAmount;
  }


  public void setOutputCurrencyAmount(BigDecimal outputCurrencyAmount) {
    this.outputCurrencyAmount = outputCurrencyAmount;
  }


  public ExchangeOffer uses(BigDecimal uses) {
    
    this.uses = uses;
    return this;
  }

   /**
   * The number of times this offer has been used.
   * @return uses
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of times this offer has been used.")

  public BigDecimal getUses() {
    return uses;
  }


  public void setUses(BigDecimal uses) {
    this.uses = uses;
  }


  public ExchangeOffer maxUses(BigDecimal maxUses) {
    
    this.maxUses = maxUses;
    return this;
  }

   /**
   * The maximum number of times this offer can be used. A value of &#x60;0&#x60; means there is no limit on how many times this offer can be used.
   * @return maxUses
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The maximum number of times this offer can be used. A value of `0` means there is no limit on how many times this offer can be used.")

  public BigDecimal getMaxUses() {
    return maxUses;
  }


  public void setMaxUses(BigDecimal maxUses) {
    this.maxUses = maxUses;
  }


  public ExchangeOffer lastUpdatedAt(BigDecimal lastUpdatedAt) {
    
    this.lastUpdatedAt = lastUpdatedAt;
    return this;
  }

   /**
   * A unix timestamp in seconds that represents the last time this offer was set or updated.
   * @return lastUpdatedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A unix timestamp in seconds that represents the last time this offer was set or updated.")

  public BigDecimal getLastUpdatedAt() {
    return lastUpdatedAt;
  }


  public void setLastUpdatedAt(BigDecimal lastUpdatedAt) {
    this.lastUpdatedAt = lastUpdatedAt;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExchangeOffer exchangeOffer = (ExchangeOffer) o;
    return Objects.equals(this.id, exchangeOffer.id) &&
        Objects.equals(this.inputCollection, exchangeOffer.inputCollection) &&
        Objects.equals(this.inputCollectionItemIds, exchangeOffer.inputCollectionItemIds) &&
        Objects.equals(this.inputCollectionItemAmounts, exchangeOffer.inputCollectionItemAmounts) &&
        Objects.equals(this.inputCurrency, exchangeOffer.inputCurrency) &&
        Objects.equals(this.inputCurrencyAmount, exchangeOffer.inputCurrencyAmount) &&
        Objects.equals(this.outputCollection, exchangeOffer.outputCollection) &&
        Objects.equals(this.outputCollectionItemIds, exchangeOffer.outputCollectionItemIds) &&
        Objects.equals(this.outputCollectionItemAmounts, exchangeOffer.outputCollectionItemAmounts) &&
        Objects.equals(this.outputCurrency, exchangeOffer.outputCurrency) &&
        Objects.equals(this.outputCurrencyAmount, exchangeOffer.outputCurrencyAmount) &&
        Objects.equals(this.uses, exchangeOffer.uses) &&
        Objects.equals(this.maxUses, exchangeOffer.maxUses) &&
        Objects.equals(this.lastUpdatedAt, exchangeOffer.lastUpdatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, inputCollection, inputCollectionItemIds, inputCollectionItemAmounts, inputCurrency, inputCurrencyAmount, outputCollection, outputCollectionItemIds, outputCollectionItemAmounts, outputCurrency, outputCurrencyAmount, uses, maxUses, lastUpdatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExchangeOffer {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    inputCollection: ").append(toIndentedString(inputCollection)).append("\n");
    sb.append("    inputCollectionItemIds: ").append(toIndentedString(inputCollectionItemIds)).append("\n");
    sb.append("    inputCollectionItemAmounts: ").append(toIndentedString(inputCollectionItemAmounts)).append("\n");
    sb.append("    inputCurrency: ").append(toIndentedString(inputCurrency)).append("\n");
    sb.append("    inputCurrencyAmount: ").append(toIndentedString(inputCurrencyAmount)).append("\n");
    sb.append("    outputCollection: ").append(toIndentedString(outputCollection)).append("\n");
    sb.append("    outputCollectionItemIds: ").append(toIndentedString(outputCollectionItemIds)).append("\n");
    sb.append("    outputCollectionItemAmounts: ").append(toIndentedString(outputCollectionItemAmounts)).append("\n");
    sb.append("    outputCurrency: ").append(toIndentedString(outputCurrency)).append("\n");
    sb.append("    outputCurrencyAmount: ").append(toIndentedString(outputCurrencyAmount)).append("\n");
    sb.append("    uses: ").append(toIndentedString(uses)).append("\n");
    sb.append("    maxUses: ").append(toIndentedString(maxUses)).append("\n");
    sb.append("    lastUpdatedAt: ").append(toIndentedString(lastUpdatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("inputCollection");
    openapiFields.add("inputCollectionItemIds");
    openapiFields.add("inputCollectionItemAmounts");
    openapiFields.add("inputCurrency");
    openapiFields.add("inputCurrencyAmount");
    openapiFields.add("outputCollection");
    openapiFields.add("outputCollectionItemIds");
    openapiFields.add("outputCollectionItemAmounts");
    openapiFields.add("outputCurrency");
    openapiFields.add("outputCurrencyAmount");
    openapiFields.add("uses");
    openapiFields.add("maxUses");
    openapiFields.add("lastUpdatedAt");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ExchangeOffer
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (ExchangeOffer.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in ExchangeOffer is not found in the empty JSON string", ExchangeOffer.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!ExchangeOffer.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ExchangeOffer` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if ((jsonObj.get("inputCollection") != null && !jsonObj.get("inputCollection").isJsonNull()) && !jsonObj.get("inputCollection").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `inputCollection` to be a primitive type in the JSON string but got `%s`", jsonObj.get("inputCollection").toString()));
      }
      // ensure the json data is an array
      if ((jsonObj.get("inputCollectionItemIds") != null && !jsonObj.get("inputCollectionItemIds").isJsonNull()) && !jsonObj.get("inputCollectionItemIds").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `inputCollectionItemIds` to be an array in the JSON string but got `%s`", jsonObj.get("inputCollectionItemIds").toString()));
      }
      // ensure the json data is an array
      if ((jsonObj.get("inputCollectionItemAmounts") != null && !jsonObj.get("inputCollectionItemAmounts").isJsonNull()) && !jsonObj.get("inputCollectionItemAmounts").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `inputCollectionItemAmounts` to be an array in the JSON string but got `%s`", jsonObj.get("inputCollectionItemAmounts").toString()));
      }
      if ((jsonObj.get("inputCurrency") != null && !jsonObj.get("inputCurrency").isJsonNull()) && !jsonObj.get("inputCurrency").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `inputCurrency` to be a primitive type in the JSON string but got `%s`", jsonObj.get("inputCurrency").toString()));
      }
      if ((jsonObj.get("outputCollection") != null && !jsonObj.get("outputCollection").isJsonNull()) && !jsonObj.get("outputCollection").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `outputCollection` to be a primitive type in the JSON string but got `%s`", jsonObj.get("outputCollection").toString()));
      }
      // ensure the json data is an array
      if ((jsonObj.get("outputCollectionItemIds") != null && !jsonObj.get("outputCollectionItemIds").isJsonNull()) && !jsonObj.get("outputCollectionItemIds").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `outputCollectionItemIds` to be an array in the JSON string but got `%s`", jsonObj.get("outputCollectionItemIds").toString()));
      }
      // ensure the json data is an array
      if ((jsonObj.get("outputCollectionItemAmounts") != null && !jsonObj.get("outputCollectionItemAmounts").isJsonNull()) && !jsonObj.get("outputCollectionItemAmounts").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `outputCollectionItemAmounts` to be an array in the JSON string but got `%s`", jsonObj.get("outputCollectionItemAmounts").toString()));
      }
      if ((jsonObj.get("outputCurrency") != null && !jsonObj.get("outputCurrency").isJsonNull()) && !jsonObj.get("outputCurrency").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `outputCurrency` to be a primitive type in the JSON string but got `%s`", jsonObj.get("outputCurrency").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ExchangeOffer.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ExchangeOffer' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ExchangeOffer> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ExchangeOffer.class));

       return (TypeAdapter<T>) new TypeAdapter<ExchangeOffer>() {
           @Override
           public void write(JsonWriter out, ExchangeOffer value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ExchangeOffer read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ExchangeOffer given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ExchangeOffer
  * @throws IOException if the JSON string is invalid with respect to ExchangeOffer
  */
  public static ExchangeOffer fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ExchangeOffer.class);
  }

 /**
  * Convert an instance of ExchangeOffer to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

